name: Run Unit Tests with Firebase Emulators

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      firebase:
        image: 'codekip/firebase-emulator:latest'
        ports:
          - 8085:8085
        options: >-
          --health-cmd "curl http://localhost:8085/ || exit 1"
          --health-interval 5s
          --health-timeout 2s
          --health-retries 10

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Start Firebase emulators
      - name: Start Firebase Emulators
        run: firebase emulators:start --only firestore,auth --project demo-test --import=./test/emulator-data --export-on-exit=./test/emulator-data --quiet &
        env:
          FIREBASE_AUTH_EMULATOR_HOST: 'localhost:9099'
          FIRESTORE_EMULATOR_HOST: 'localhost:8080'

      # Run your unit tests
      - name: Run Unit Tests
        run: npm run test
        env:
          FIREBASE_AUTH_EMULATOR_HOST: 'localhost:9099'
          FIRESTORE_EMULATOR_HOST: 'localhost:8080'