name: Run Unit Tests with Firebase Emulators

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Set up Node.js
        uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        env:
            FIREBASE_AUTH_EMULATOR_HOST: 'localhost:9099'
            FIRESTORE_EMULATOR_HOST: 'localhost:8080'
      - name: Start Firebase Emulators and Run Tests
        run: npm run unit-test
        env:
            FIREBASE_AUTH_EMULATOR_HOST: 'localhost:9099'
            FIRESTORE_EMULATOR_HOST: 'localhost:8080'
      - name: Stop Firebase Emulators
        if: always()
        run: firebase emulators:stop